# Workflow Name
name: sample workflow to run shell commands
#Action on repository like push,issue,pull etc
on: [push]
#Define jobs

jobs:
  run-shell-command-fist-job:
    runs-on: ubuntu-latest
#define steps in a job
    steps:
 # a step can perfom an action or shell/commands
      - name: display a String
        run: echo "I am form Bash shell"
      - name: multi line scripts
        run: |
          node -v
          npm -v
      - name: "Python commands"
        run: |
          import platform
          print(platform.processor())
          print("Hello World from ubuntu!!!")
        shell: python

  run-windows-command-fist-job:
    runs-on: windows-latest
#define steps in a job
    steps:
 # a step can perfom an action or shell/commands
      - name: display current directory in power shell
        run: Get-Location
      - name: Directory in Bash shell
        run: pwd
        shell: bash
      - name: "Python commands"
        run: |
          import platform
          print(platform.processor())
          print("Hello World from windows!!!")
        shell: python