# Workflow Name
name: sample workflow to run shell commands
#Action on repository like push,issue,pull etc
on: [push,pull_request]
#Define jobs

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
#define steps in a job
    steps:
      - name: display a String
# a step can perfom an action or shell/commands
        run: echo "Hello World"
      - name: multi line scripts
        run: |
          node -v
          npm -v
